### ISSUE TITLE
Duplicate tags in advanced search Morphology

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian-data#10]
In advanced search tab, Morphology, in the search window, some tags are listed twice, namely there are 2 XP, 2 VP, 2 Cl, and 2 Cmp. I have cleaned the Morphology column in the source database, so this problem should disappear when the data will be read into the website next time.

**Comment by bast** [comment]
Can you please check whether this is still an issue?

**Comment by Labrus** [comment]
I have checked. Those duplicate tags are no longer an issue. Some more duplicates came up, I have not corrected them in the database, so next time you will read in the data, there should be no problem here.

**Comment by bast** [comment]
OK keeping open until next data read.

**Comment by bast** [comment]
Just made a new data import. Hence closing.
