### ISSUE TITLE
How can I fix two duplicative numbers - ID 256 - ?

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian-data#12]
We just found a mistake in the database: there are two constructions that have the same ID number 256, but the constructions are different and we need to keep both. Only one of these constructions is present now in the list on the website. 

256 | оставить-Imp NP-Acc в покое! | оставить-Imper NP-Acc в покое! | Оставь меня в покое!
-- | -- | -- | --
256 | NP-Nom какой Cop | NP-Nom какой Cop | Посмотрите, ужас какой!

I am ready to do anything, so that we disturb your code the least, so please let me know what is best to do here? I can delete the one with the duplicate number or give it a different number.

**Comment by bast** [comment]
I anyway have to do the conversion from spreadsheet every time I am updating the data so after you fix it in the spreadsheet it should be picked up correctly.

**Comment by Labrus** [comment]
Ok. I deleted the first of these two entries from the database (because this one not described).
256 | оставить-Imp NP-Acc в покое! | оставить-Imper NP-Acc в покое! | Оставь меня в покое!
-- | -- | -- | --
Now we have only one construction with ID 256:
256 | NP-Nom какой Cop | NP-Nom какой Cop | Посмотрите, ужас какой!
-- | -- | -- | --
