### ISSUE TITLE
What should I do with 5 constructions-duplicates?

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian-data#13]
We discovered that there are 5 constructions in the database that duplicate other 5 constructions in the database. They all have different ID numbers with their counterparts. For example constructions ID 1531 and ID 1790 are identical and we want only keep 1531. 

I am ready to do anything you say to disturb your code the least possible. One solution is just delete these entries. Another solution that maybe you like more is that we keep these numbers but put there five different constructions (we have such a list for the future) that will not be duplicative. I am asking you because I do not know how you code different entries. If you have a specific construction assigned to a specific number or not, I do not want to damage the code. So, I can do whatever you say, what is the easiest option for you.

The numbers of constructions to delete or to fill with different content are:
ID 403, 1116, 1668, 1673, 1790.
I coloured their lines in red in the database.
I do not know how they appeared in the database.

**Comment by bast** [comment]
I recommend to remove the rows which are duplicate. My conversion scripts should then pick it up. Keeping this issue open as reminder to check that 5 files then disappeared.

**Comment by Labrus** [comment]
Ok. I have deleted those 5 rows.
