### ISSUE TITLE
I corrected typos in tags - read in the database anew

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian-data#14]
In advanced search, I went through all typos and other errors that occurred because of the data in the database and I corrected now everything I noticed. When you have time, please read in the data again from the google spreadsheet into the website, so that I can check whether all my corrections are reflected in the search windows in Advanced Search. Please make sure you read in not only the descriptions of constructions but also all the tags they have.

**Comment by bast** [comment]
OK I will update the data and then inform you and then you can check whether all tags are in the right place.

**Comment by Labrus** [comment]
Great!

**Comment by Labrus** [comment]
The typos that were corrected disappeared indeed (hooray!), but now I found some more of them and in the process of fixing them. I will ask you to renew the website again in a few days.

**Comment by bast** [comment]
OK closing this then.
