### ISSUE TITLE
Update the structure of YAML template

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian-data#21]
We have added two more fields to the description of each construction, namely EQUIVALENT (English) and EQUIVALENT (Norwegian). The content comes from columns I and J called "English equivalent" and "Norwegian equivalent" accordingly, in the spreadsheet google database. We suggest that we represent this information in the YAML template, so that the English and Norwegian equivalents of each construction would show up on the website. We suggest that in the structure of YAML they would appear when the user opens "Additional information", on the very top, before the field COMMON FILLERS. Here is an example of construction #4:
<img width="1086" alt="Screen Shot 2022-07-06 at 18 15 53" src="https://user-images.githubusercontent.com/63615172/177600010-89400ff1-a4e0-49f9-9bed-4520d280c897.png">

So, on the top of additional information, before COMMON FILLERS, there will be two new fields:
EQUIVALENT (English)
...
EQUIVALENT (Norwegian)
...

The content of this fields can appear in the same or in the next line and be all in a single line as a text
The content sometimes contains symbols like "/ " and "," and ";" - this is because sometimes there are several equivalents that are proposed.
I hope this would not disturb the code. If you need to put this content into the quotation marks like " " in order to deal with the commas and columns that are in the content, it is fine.

**Comment by bast** [comment]
Is this still relevant? Hasn't this been implemented?

**Comment by bast** [comment]
Ah it's in #23 but they were not linked so I did not connect the dots.

**Comment by bast** [comment]
I assume this has been fixed in #23 but please reopen the issue if I misunderstood that.
