### ISSUE TITLE
One change in database structure

### ISSUE THREAD

**Issue by Labrus** [constructicon/russian-data#6]
Radovan should take into account that we had to make a change in the structure of the database by adding one more column
BQ called Polarity value - this is one of Semantic tags that is included in search. There are 3 values there: "Negative", "Positive" and "Both Negative and Positive".

I also had to update the values inside semantic tags Assessment and Attitude.
Assessment has 5 values:
- Assessment in relation to knowledge
- Assessment in relation to norms/expectations
- Assessment in relation to quantification
- Assessments specific to people
- General assessment

Attitude has 5 values:
- Acceptance
- Capacity/Preferences
- Dissatisfaction
- Emotional Attitude
- Mental Attitude

Some constructions carry more than one of these values/tagd, and if so the tags are separated by the comma ","
If the tags with "/" are problematic, I can replace "/" with "and". In the article that described these tags we used "/": Assessment in relation to norms/expectations, Capacity/Preferences.

Inside column B "Family" I entered the labels of the smaller of constructions from our article that are sub-groups of the tags indicated above.

**Comment by bast** [comment]
Suggestion: please create two issues from this in future. Because there is one issue for me to add one more data entry for column "Polarity value". And there there are one or two problems discussed which look unrelated and where it is not clear to me whether I should do something about it or not (the discussion about tags).

**Comment by bast** [comment]
Split into #8 and #9.
