### ISSUE TITLE
Constructions with more than one separator tag

### ISSUE THREAD

**Issue by bast** [constructicon/russian-data#9]
Text below is copied from #6:

---

I also had to update the values inside semantic tags Assessment and Attitude.
Assessment has 5 values:
- Assessment in relation to knowledge
- Assessment in relation to norms/expectations
- Assessment in relation to quantification
- Assessments specific to people
- General assessment

Attitude has 5 values:
- Acceptance
- Capacity/Preferences
- Dissatisfaction
- Emotional Attitude
- Mental Attitude

Some constructions carry more than one of these values/tagd, and if so the tags are separated by the comma ","
If the tags with "/" are problematic, I can replace "/" with "and". In the article that described these tags we used "/": Assessment in relation to norms/expectations, Capacity/Preferences.

Inside column B "Family" I entered the labels of the smaller of constructions from our article that are sub-groups of the tags indicated above.

**Comment by bast** [comment]
Issue copied from #6

**Comment by bast** [comment]
Is this done/solved? Or is this a note for future work?

**Comment by Labrus** [comment]
This looks perfect on the website now in Advanced search, / is not a separate there, it is correct. We can close this issue.
